POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Super Widget",
  "status": "active", 
  "categoryId": "b84cbb9e-97fa-4f2e-a670-3627b81265c1",
  "price": 299.99,
  "remaining": 50,
  "description": "A high-quality widget that surpasses all others.",
  "tags": ["gadget", "electronics", "premium"],
  "couponId": "c12dabc2-9f23-4fa3-8d6f-0a674b98a2c5",
  "suggesionId": "d74b1234-6f47-41a5-9e3d-67df2b3a1b6c"
}
