PATCH http://localhost:3000/categories
Content-Type: application/json

{
  "firstName": "Mark",
  "lastName": "Doe",
  "username": "mark15",
  "email": "mark15@doe.com",
  "isActive": true,
  "password": "Password123@"
}